### ISSUE TITLE
Add Max functionality to Submissions

### ISSUE THREAD

**Issue by khoj-pez** [Theknickerbocker/UB_Grader#137]
As of now, submission routes can only send out latest submission(s) as the response but the front end should be able the specify if they want latest submission(s) or the max submission(s)(submission with the maximum score). The latter needs to be implemented.

Create two routes:
1 - To return a list of submissions of all users in an assignment based on max score.
2 - To return a list of submissions of a particular user in all assignments of a course based on max score.

**Comment by khoj-pez** [comment]
Hey Ryan,
I haven't heard from you regarding your status on the issue. Just thought I'd check up and see if everything is good. Let me know if you are stuck somewhere or need help. @RyanDanielOMara

**Comment by RyanDanielOMara** [comment]
Hey Dhruv,
No problems currently, going to have a deeper look at this tomorrow and I'll let you know if I have any issues.  @dhruv0215

**Comment by khoj-pez** [comment]
@RyanDanielOMara Awesome. My recommendation would be to look at server/dummyData.js. You can create sample submissions there with certain scores. After you've done that, you can simply add the functionality for the routes to server/routes/routes.js and server/controllers/SubmissionController.js and test it to see if you get the required response based on the submissions in the dummy data when calling a route that you create.

**Comment by khoj-pez** [comment]
@RyanDanielOMara The backend team will be out of town starting Friday till Sunday night. The response during the upcoming weekend will not be as fast. Please do let me know if you have any questions before that. If any questions come up during the weekend, I will most likely reply back by the end of that day at some point during the night. Just thought I'd give you a heads up.

**Comment by RyanDanielOMara** [comment]
@dhruv0215 Just submitted a pull request.  I wasn't able to add you as a reviewer so I wanted to let you know.

**Comment by khoj-pez** [comment]
@RyanDanielOMara added the required functionality.
