### ISSUE TITLE
Webserver crashes if Tango feedback doesn't have valid JSON

### ISSUE THREAD

**Issue by adhishchugh** [Theknickerbocker/UB_Grader#144]
Need to add error handling before we call JSON.parse

**Comment by Searay-330** [comment]
the real question is why isnt the backend giving valid json

**Comment by dhruv0215** [comment]
Are you talking about Tango backend or submissions?

**Comment by adhishchugh** [comment]
I'm not sure you understand. This is for the feedback file we get from Tango. Has nothing to do with the backend "giving" a valid JSON. The backend is receiving a file here.

**Comment by Searay-330** [comment]
I was just meming cause that was a huge problem not to long ago but yeah this is a serious bug we should get fixed

**Comment by adhishchugh** [comment]
Ah. Yes. We'll fix it soon.

**Comment by khoj-pez** [comment]
This is solved
