### ISSUE TITLE
Can't create a course with an email that's not already in the database

### ISSUE THREAD

**Issue by khoj-pez** [Theknickerbocker/UB_Grader#179]
Title
<img width="954" alt="screen shot 2017-10-24 at 11 25 16 am" src="https://user-images.githubusercontent.com/18632120/31952592-f5b44ff6-b8ae-11e7-8915-501d1954117a.png">

**Comment by dhruv0215** [comment]
<img width="954" alt="screen shot 2017-10-24 at 11 25 16 am" src="https://user-images.githubusercontent.com/18632120/31952592-f5b44ff6-b8ae-11e7-8915-501d1954117a.png">

**Comment by Searay-330** [comment]
This I doubt is a front end problem

**Comment by adhishchugh** [comment]
I'm guessing you're calling two routes, one that creates a course and then another that adds the user to that course with the instructor role?
@dhruv0215 are you able to add someone (who isn't in the DB) as an instructor after the course is created? Using the add user to course page?
If so, I think the problem might be that the second backend route is being called before the first one returns.

**Comment by Searay-330** [comment]
Ill check it out today and see what I can turn up

**Comment by khoj-pez** [comment]
I had to drop the db. Closed because everything seems to work fine.
