### ISSUE TITLE
CSV "complete" import design is bad for instructors

### ISSUE THREAD

**Issue by rhanulewicz** [Theknickerbocker/UB_Grader#234]
Imagine this scenario:

An instructor has just been assigned to their new course. They import their class roster of students as "complete". One of two things can happen:
A) The roster includes the instructor, which re-adds him to the course as a student instead of an instructor.
B) The roster does not include the instructor, and the instructor gets removed from his own course.

Solutions include (pick one):
- Allow CSV file to specify role (student, instructor)
- Remove "complete" functionality

**Comment by adhishchugh** [comment]
Or we don’t do anything to the user that uploaded the roster. We should have a separate page to remove a user from a course anyway.

**Comment by rhanulewicz** [comment]
Also a good idea.

**Comment by adhishchugh** [comment]
I can only think of two use cases for the complete functionality. The instructor uploads the roster at the start of the semester and does another upload with “complete” set to true after the add/drop date and finally after the resign date. Also, perhaps the “complete” shouldn’t remove users but mark them as dropped. Then they can’t submit new assignments but still can look at stuff they submitted before they dropped. This would mimic the current AutoLab.

**Comment by techmamba24** [comment]
It's import "class roster"... i don't think a class roster should include the instructor.... nonetheless I can add a check that even if complete is "true", it won't remove the instructor

**Comment by rhanulewicz** [comment]
That would work

**Comment by techmamba24** [comment]
The import roster functionality as of now only adds students to courses .. there is no way to specify the role of person being added in the csv file so this does not apply .. import roster automatically adds everyone in the csv file to the course with the course role of 'student'.
